source 'http://mmamic@rs-build.int.sedamit.hr/repo/r/~mmamic/podspecs.git'
#source 'https://github.com/CocoaPods/Specs.git'

# Uncomment this line to define a global platform for your project
 platform :ios, '10.0'

target 'Sample' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  pod 'Pozzito'
  pod 'PozzitoUI'
end
